### ISSUE TITLE
IBM isn't allowing HTTP connections now SSL is required.

### ISSUE THREAD

**Issue by devpolish** [AlexYanai/cloudant#6]
For any reason IBM Cloudant is only allowing HTTPS traffic, I tried to create a new config file specifying the 80 port but it didn't work. My solution has changed the port and specify SSL usage.

Actually, I've opened a new PR. Thank you very much.
https://github.com/AlexYanai/cloudant/pull/7

**Comment by AlexYanai** [comment]
@devpolish thanks for the heads up, I've merged your changes.
